name: Continous Delivery
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Simulação CD
        uses: actions/upload-artifact@v4
        with:
          name: prévias.zip
          path: |
            '**.py'
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Baixar Arquivos
        uses: actions/download-artifact@v5
        with:
          name: prévias.zip
      
      - name: Display structure of downloaded files
        run: ls -R
