name: Discord Notifications

on:
  push:  
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Send Discord Notification
        uses: sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
          status: ${{ job.status }}  
          message: "Commit em **${{ github.repository }}** por **${{ github.actor }}** terminou com status **${{ job.status }}**"
